### ISSUE TITLE
Unable to run with shareware version.

### ISSUE THREAD

**Issue by fabiensanglard** [nukeykt/PCDoom-v2#20]
Running PCDoom-v2 with doom1.wad doesn't work, the error message is:

W_GetNumForName: M_EPI4 not found!

Which refers to a lump the shareware doesn't have.

Starting with a demo doesn't crash:

C:\PCDOOM2>DOOM.EXE -timedemo demo1

**Comment by fabiensanglard** [comment]
Submitted pull request: https://github.com/nukeykt/PCDoom-v2/pull/21

**Comment by AXDOOMER** [comment]
I would say that this is normal because PCDoom-v2 emulates the Ultimate Doom version of the Doom v1.9 executable, which has this bug because this version wasn't meant to be run with the shareware or the registered IWAD, only the Ultimate Doom. If you try the IWAD from the registered version, you'd get the same crash and your fix doesn't resolve it. 

Also, please check if this fix still makes it possible to select the fourth episode. By looking at the fix, I see that it won't be drawn on the screen but you may still be able to move the skull cursor over its position where it's supposed to be in the menu.

**Comment by AXDOOMER** [comment]
Hi Fabien,

One way to fix it would be to add a check at the end of `M_Init`.

    // Remove the fourth episode from the EpiDef array if the "m_epi4" lump is not found
    if (W_CheckNumForName("m_epi4")<0)
        EpiDef.numitems--;

I haven't tested this code, but something with this logic would also work with the registered version of Doom, assuming that `numitems` is always equals to the size of the array which contains the four episodes.

**Comment by nukeykt** [comment]
I think i should add earlier versions emulation using '#ifdef's. Emulation of versions down to 1.666 should be easy.

**Comment by AXDOOMER** [comment]
> I think i should add earlier versions emulation using '#ifdef's.

I think that's a great idea.

**Comment by nukeykt** [comment]
Fixed in 886a838
